service: shelltest
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  memorySize: 2048
  timeout: 15
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
